---
packages:
  ## misc tools
  - vim
  - wget
  - mlocate
  - git
  ## bind-specific packages
  - bind
  - bind-utils
  - bind-chroot
  ## firewall
  - firewalld
  ## monitoring
  - nrpe
  - nagios-plugins-all
