---
# Install and update system packages
- include: packages.yml
  tags:
    - packages

# Configure BIND
- include: config.yml
  tags:
    - config

# Compile and write zone files
- include: records.yml
  tags:
    - records
