---
- name: Ensure ceph packages are not present.
  zypper:
    name: "{{ item }}"
    state: absent
  with_items: ceph_packages_to_remove
  tags:
    - remove-ceph

- name: Ensure ceph dependency packages are not present.
  zypper:
    name: "{{ item }}"
    state: absent
  with_items: ceph_dependency_packages_to_remove
  tags:
    - remove-ceph-dependency

- name: Remove packages
  zypper:
    name: "{{ item }}"
    state: absent
  with_items: packages_to_remove
  when: packages_to_remove|length > 0

- name: Install packages
  zypper:
    name: "{{ item }}"
    state: present
  with_items: packages
  when: packages|length > 0

- name: Upgrade packages
  zypper:
    name: "{{ item }}"
    state: latest
  with_items: packages_to_upgrade
  when: packages_to_upgrade|length > 0
